name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  specs:
    name: specs
    runs-on: actuated-arm64-1cpu-4gb
    steps:
      - name: Check specs
        run: |
          cat /lib/modules/$(uname -r)/.config
        
